// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "head.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace head_msg {

namespace {

const ::google::protobuf::EnumDescriptor* CSMsgName_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_head_2eproto() {
  protobuf_AddDesc_head_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "head.proto");
  GOOGLE_CHECK(file != NULL);
  CSMsgName_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_head_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_head_2eproto() {
}

void protobuf_AddDesc_head_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nhead.proto\022\010head_msg*\202\?\n\tCSMsgName\022\023\n\017"
    "CSMessageHeader\020\000\022\r\n\tErrorCode\020\001\022\017\n\013CSEr"
    "rorCode\020\002\022\025\n\021CSCheckSessionReq\020\003\022\025\n\021CSCh"
    "eckSessionRsp\020\004\022\024\n\020CSGetRoleListReq\020\005\022\024\n"
    "\020CSGetRoleListRsp\020\006\022\023\n\017CSCreateRoleReq\020\007"
    "\022\023\n\017CSCreateRoleRsp\020\010\022\016\n\nCSLoginReq\020\t\022\016\n"
    "\nCSLoginRsp\020\n\022\020\n\014CSCrtRoleReq\020\013\022\020\n\014CSDel"
    "RoleReq\020\014\022\020\n\014CSCrtRoleRsp\020\r\022\023\n\017CSQuerySh"
    "ardReq\020\016\022\020\n\014CSServerBase\020\017\022\017\n\013CSShardBas"
    "e\020\020\022\023\n\017CSQueryShardRsp\020\021\022\017\n\013FlushOnline\020"
    "\022\022\017\n\013FlushServer\020\023\022\021\n\rPlayerOffline\020\024\022\r\n"
    "\tCSPingReq\020\025\022\r\n\tCSPingRsp\020\026\022\020\n\014CSTaskAcc"
    "ept\020\027\022\021\n\rCSNickNameReq\020\030\022\021\n\rCSNickNameRs"
    "p\020\031\022\032\n\026CSLoginAnnouncementReq\020\032\022\030\n\023Basic"
    "UserBattleInfo\020\320\017\022\022\n\rUserSkillPart\020\321\017\022\022\n"
    "\rUserSkillInfo\020\322\017\022\022\n\rBasicUserInfo\020\323\017\022\022\n"
    "\rCSEnterMapReq\020\324\017\022\022\n\rCSEnterMapRsp\020\325\017\022\022\n"
    "\rCSLeaveMapRsp\020\326\017\022\025\n\020CSGetMapUsersReq\020\327\017"
    "\022\025\n\020CSGetMapUsersRsp\020\330\017\022\026\n\021CSGetUserSkil"
    "lReq\020\331\017\022\026\n\021CSGetUserSkillRsp\020\332\017\022\025\n\020CSGet"
    "UserInfoReq\020\333\017\022\025\n\020CSGetUserInfoRsp\020\334\017\022\026\n"
    "\021CSAddUserSkillReq\020\335\017\022\026\n\021CSAddUserSkillR"
    "sp\020\336\017\022\027\n\022CSUserSkillDiffReq\020\337\017\022\027\n\022CSUser"
    "SkillDiffRsp\020\340\017\022\032\n\025CSSkillUpdateValidRsq"
    "\020\341\017\022\016\n\tCSWalkReq\020\342\017\022\016\n\tCSWalkRsp\020\343\017\022\017\n\nC"
    "SItemAttr\020\344\017\022\020\n\013CSEquipHole\020\345\017\022\022\n\rEquipm"
    "entBase\020\346\017\022\024\n\017SpiritStoneBase\020\347\017\022\016\n\tMano"
    "rBase\020\350\017\022\017\n\nCSItemInfo\020\351\017\022\022\n\rCSAllItemsR"
    "eq\020\352\017\022\022\n\rCSAllItemsRsp\020\353\017\022\021\n\014CSItemAddRs"
    "p\020\354\017\022\024\n\017CSItemRemoveReq\020\355\017\022\024\n\017CSItemRemo"
    "veRsp\020\356\017\022\021\n\014CSItemUseReq\020\357\017\022\021\n\014CSItemUse"
    "Rsp\020\360\017\022\022\n\rCSItemMoveReq\020\361\017\022\022\n\rCSItemMove"
    "Rsp\020\362\017\022\024\n\017CSItemUpdateRsp\020\363\017\022\023\n\016CSItemOr"
    "derReq\020\364\017\022\036\n\031CSItemMoveToRecycleBinReq\020\365"
    "\017\022\036\n\031CSItemMoveToRecycleBinRsp\020\366\017\022\034\n\027CSR"
    "epoRecycleBinItemReq\020\367\017\022\034\n\027CSRepoRecycle"
    "BinItemRsp\020\370\017\022\023\n\016CSInstanceInfo\020\371\017\022\022\n\rCS"
    "InstanceReq\020\372\017\022\022\n\rCSInstanceRsp\020\373\017\022\034\n\027CS"
    "GetUGCityBoxRewardReq\020\374\017\022\034\n\027CSGetUGCityB"
    "oxRewardRsp\020\375\017\022\r\n\010CSReward\020\376\017\022\021\n\014CSLevel"
    "UpRsp\020\377\017\022\035\n\030CSBasicUserBattleInfoRsp\020\200\020\022"
    "\033\n\026CSSearchSpiritStoneReq\020\201\020\022\033\n\026CSSearch"
    "SpiritStoneRsp\020\202\020\022\034\n\027CSSpiritStoneMoveBa"
    "gReq\020\203\020\022\034\n\027CSSpiritStoneMoveBagRsp\020\204\020\022\034\n"
    "\027CSSpiritStoneLevelUpReq\020\205\020\022\034\n\027CSSpiritS"
    "toneLevelUpRsp\020\206\020\022\031\n\024CSSpiritStoneToSPRe"
    "q\020\207\020\022\031\n\024CSSpiritStoneToSPRsp\020\210\020\022\033\n\026CSGet"
    "ExchangeSSInfoReq\020\211\020\022\023\n\016ExchangeSSInfo\020\212"
    "\020\022\033\n\026CSGetExchangeSSInfoRsp\020\213\020\022\022\n\rCSAddM"
    "anorReq\020\214\020\022\022\n\rCSAddManorRsp\020\215\020\022\027\n\022CSWarm"
    "SportLvUpReq\020\216\020\022\027\n\022CSWarmSportLvUpRsp\020\217\020"
    "\022\022\n\rCSManorOptReq\020\220\020\022\022\n\rCSManorOptRsp\020\221\020"
    "\022\021\n\014CSMonListReq\020\222\020\022\014\n\007MonInfo\020\223\020\022\021\n\014CSM"
    "onListRsp\020\224\020\022\026\n\021CSSetMonStatusReq\020\225\020\022\026\n\021"
    "CSSetMonStatusRsp\020\226\020\022\026\n\021CSPVPQueryRoomRe"
    "q\020\227\020\022\020\n\013PVPRoomBase\020\230\020\022\026\n\021CSPVPQueryRoom"
    "Rsp\020\231\020\022\025\n\020CSPVPBaseInfoRsp\020\232\020\022\027\n\022CSPVPCr"
    "eateRoomReq\020\233\020\022\025\n\020CSPVPJoinRoomReq\020\234\020\022\020\n"
    "\013PVPSeatBase\020\235\020\022\025\n\020CSPVPJoinRoomRsp\020\236\020\022\025"
    "\n\020CSPVPExitRoomReq\020\237\020\022\025\n\020CSPVPExitRoomRs"
    "p\020\240\020\022\026\n\021CSPVPCloseRoomRsp\020\241\020\022\027\n\022CSPVPCha"
    "ngeSeatReq\020\242\020\022\022\n\rCSPVPReadyReq\020\243\020\022\030\n\023CSP"
    "VPCancelReadyReq\020\244\020\022\024\n\017CSPVPKickoffReq\020\245"
    "\020\022\024\n\017CSPVPKickoffRsp\020\246\020\022\022\n\rCSPVPStartReq"
    "\020\247\020\022\022\n\rCSPVPStartRsp\020\250\020\022\024\n\017CSPPVEBattleR"
    "eq\020\251\020\022\024\n\017CSPPVEBattleRsp\020\252\020\022\026\n\021CSPVEQuer"
    "yRoomReq\020\253\020\022\020\n\013PVERoomBase\020\254\020\022\026\n\021CSPVEQu"
    "eryRoomRsp\020\255\020\022\025\n\020CSPVEBaseInfoRsp\020\256\020\022\027\n\022"
    "CSPVECreateRoomReq\020\257\020\022\025\n\020CSPVEJoinRoomRe"
    "q\020\260\020\022\034\n\027CSPVEJoinRoomFailureRsp\020\261\020\022\020\n\013PV"
    "ESeatBase\020\262\020\022\025\n\020CSPVEJoinRoomRsp\020\263\020\022\025\n\020C"
    "SPVEExitRoomReq\020\264\020\022\025\n\020CSPVEExitRoomRsp\020\265"
    "\020\022\026\n\021CSPVECloseRoomRsp\020\266\020\022\022\n\rCSPVEReadyR"
    "eq\020\267\020\022\030\n\023CSPVECancelReadyReq\020\270\020\022\024\n\017CSPVE"
    "KickoffReq\020\271\020\022\024\n\017CSPVEKickoffRsp\020\272\020\022\022\n\rC"
    "SPVEStartReq\020\273\020\022\022\n\rCSPVEStartRsp\020\274\020\022\016\n\tC"
    "SPVAIReq\020\275\020\022\022\n\rCSPVAIInfoReq\020\276\020\022\022\n\rCSPVA"
    "IInfoRsq\020\277\020\022\016\n\tCSPVP2Req\020\300\020\022\024\n\017CSPVP2Can"
    "celReq\020\301\020\022\023\n\016CSPVXRewardRsp\020\302\020\022\027\n\022CSEqui"
    "pInlayGemReq\020\303\020\022\027\n\022CSEquipInlayGemRsp\020\304\020"
    "\022\026\n\021CSResetGemAttrReq\020\305\020\022\026\n\021CSResetGemAt"
    "trRsp\020\306\020\022\033\n\026CSEquipmentStrengthReq\020\307\020\022\033\n"
    "\026CSEquipmentStrengthRsp\020\310\020\022\032\n\025CSEquipmen"
    "tComposeReq\020\311\020\022\032\n\025CSEquipmentComposeRsp\020"
    "\312\020\022\022\n\rCSTaskInfoReq\020\313\020\022\r\n\010TaskInfo\020\314\020\022\022\n"
    "\rCSTaskInfoRsp\020\315\020\022\024\n\017CSTaskDoStepReq\020\316\020\022"
    "\024\n\017CSTaskDoStepRsp\020\317\020\022\021\n\014CSTaskLogReq\020\320\020"
    "\022\021\n\014CSTaskLogRsp\020\321\020\022\024\n\017CSTaskStatusReq\020\322"
    "\020\022\024\n\017CSTaskStatusRsp\020\323\020\022\022\n\rDailyTaskInfo"
    "\020\324\020\022\027\n\022CSDailyTaskInfoReq\020\325\020\022\027\n\022CSDailyT"
    "askInfoRsp\020\326\020\022\031\n\024CSAcceptDailyTaskReq\020\327\020"
    "\022\031\n\024CSAcceptDailyTaskRsp\020\330\020\022\031\n\024CSGiveUpD"
    "ailyTaskReq\020\331\020\022\031\n\024CSGiveUpDailyTaskRsp\020\332"
    "\020\022\034\n\027CSGetDailyTaskRewardReq\020\333\020\022\034\n\027CSGet"
    "DailyTaskRewardRsp\020\334\020\022#\n\036CSNotifyUpdateD"
    "ailyTaskInfoRsp\020\335\020\022\034\n\027CSGetDailyGoalRewa"
    "rdReq\020\336\020\022\034\n\027CSGetDailyGoalRewardRsp\020\337\020\022\030"
    "\n\023CSGetDailyRewardReq\020\340\020\022\030\n\023CSGetDailyRe"
    "wardRsp\020\341\020\022\036\n\031CSSelectPVAIACCURewardReq\020"
    "\342\020\022\036\n\031CSSelectPVAIACCURewardRsp\020\343\020\022\027\n\022CS"
    "AttributesSetReq\020\344\020\022\024\n\017CSAttributesReq\020\345"
    "\020\022\024\n\017CSAttributesRsp\020\346\020\022\021\n\014CSOnceSetReq\020"
    "\347\020\022\016\n\tCSOnceReq\020\350\020\022\016\n\tCSOnceRsp\020\351\020\022\023\n\016CS"
    "TrainInfoReq\020\352\020\022\023\n\016CSTrainInfoRsp\020\353\020\022\017\n\n"
    "CSTrainReq\020\354\020\022\017\n\nCSTrainRsp\020\355\020\022\030\n\023CSTrai"
    "nDetermineReq\020\356\020\022\030\n\023CSTrainDetermineRsp\020"
    "\357\020\022\021\n\014CSExploreReq\020\360\020\022\021\n\014CSExploreRsp\020\361\020"
    "\022\032\n\025CSExploreDetermineReq\020\362\020\022\032\n\025CSExplor"
    "eDetermineRsp\020\363\020\022\024\n\017CSQueryDowerReq\020\364\020\022\024"
    "\n\017CSQueryDowerRsp\020\365\020\022\023\n\016CSDowerInfoReq\020\366"
    "\020\022\023\n\016CSDowerInfoRsp\020\367\020\022\017\n\nCSDowerReq\020\370\020\022"
    "\017\n\nCSDowerRsp\020\371\020\022\023\n\016CSABMonsterReq\020\372\020\022\023\n"
    "\016CSABMonsterRsp\020\373\020\022\024\n\017CSAutoBattleReq\020\374\020"
    "\022\024\n\017CSAutoBattleRsp\020\375\020\022\022\n\rCSABRewardRsp\020"
    "\376\020\022\032\n\025CSCancelAutoBattleReq\020\377\020\022\032\n\025CSCanc"
    "elAutoBattleRsp\020\200\021\022\033\n\026CSExchangeParamete"
    "rReq\020\201\021\022\033\n\026CSExchangeParameterRsp\020\202\021\022\021\n\014"
    "ShopItemInfo\020\203\021\022\026\n\021CSGetShopItemsReq\020\204\021\022"
    "\026\n\021CSGetShopItemsRsp\020\205\021\022\025\n\020CSBuyShopItem"
    "Req\020\206\021\022\025\n\020CSBuyShopItemRsp\020\207\021\022\025\n\020CSGetUs"
    "erItemReq\020\210\021\022\025\n\020CSGetUserItemRsp\020\211\021\022\033\n\026C"
    "SGetUserAttributesReq\020\212\021\022\033\n\026CSGetUserAtt"
    "ributesRsp\020\213\021\022\035\n\030CSNotifyMoneyConfInfoRs"
    "p\020\214\021\022\035\n\030CSNotifyLevelConfInfoRsp\020\215\021\022\033\n\026C"
    "SNotifyVipConfInfoRsp\020\216\021\022\032\n\025CSNotifyCliS"
    "ysFlagRsp\020\217\021\022\020\n\013PartnerInfo\020\220\021\022\020\n\013CSNear"
    "ByReq\020\221\021\022\020\n\013CSNearByRsp\020\222\021\022\025\n\020CSPartnerI"
    "nfoReq\020\223\021\022\024\n\017CSAddPartnerReq\020\224\021\022\024\n\017CSDel"
    "PartnerReq\020\225\021\022\025\n\020CSPartnerInfoRsp\020\226\021\022\024\n\017"
    "CSAddPartnerRsp\020\227\021\022\024\n\017CSDelPartnerRsp\020\230\021"
    "\022\014\n\007DndInfo\020\231\021\022\020\n\013CSAddDndReq\020\232\021\022\021\n\014CSDn"
    "dInfoReq\020\233\021\022\020\n\013CSDelDndReq\020\234\021\022\021\n\014CSDndIn"
    "foRsp\020\235\021\022\020\n\013CSAddDndRsp\020\236\021\022\020\n\013CSDelDndRs"
    "p\020\237\021\022\016\n\tCSNoteReq\020\240\021\022\016\n\tCSNoteRsp\020\241\021\022\017\n\n"
    "CSNoteShow\020\242\021\022\016\n\tCSMailReq\020\243\021\022\017\n\nAttachI"
    "tem\020\244\021\022\016\n\tCSMailRsp\020\245\021\022\r\n\010MailList\020\246\021\022\022\n"
    "\rCSMailListReq\020\247\021\022\022\n\rCSMailListRsp\020\250\021\022\021\n"
    "\014CSDelMailReq\020\251\021\022\021\n\014CSDelMailRsp\020\252\021\022\023\n\016C"
    "SGetAttachReq\020\253\021\022\023\n\016CSGetAttachRsp\020\254\021\022\021\n"
    "\014CSNewMailRsp\020\255\021\022\026\n\021CSActivityListReq\020\256\021"
    "\022\022\n\rActivity_Step\020\257\021\022\022\n\rActivity_Info\020\260\021"
    "\022\026\n\021CSActivityListRsp\020\261\021\022\033\n\026CSGetActivit"
    "yRewardReq\020\262\021\022\033\n\026CSGetActivityRewardRsp\020"
    "\263\021\022\034\n\027CSUpdateActivityInfoRsp\020\264\021\022\031\n\024CSDe"
    "lActivityInfoRsp\020\265\021\022\027\n\022CSCDEFQueryRoomRe"
    "q\020\266\021\022\021\n\014CDEFRoomBase\020\267\021\022\027\n\022CSCDEFQueryRo"
    "omRsp\020\270\021\022\026\n\021CSCDEFBaseInfoRsp\020\271\021\022\030\n\023CSCD"
    "EFCreateRoomReq\020\272\021\022\026\n\021CSCDEFJoinRoomReq\020"
    "\273\021\022\035\n\030CSCDEFJoinRoomFailureRsp\020\274\021\022\021\n\014CDE"
    "FSeatBase\020\275\021\022\026\n\021CSCDEFJoinRoomRsp\020\276\021\022\026\n\021"
    "CSCDEFExitRoomReq\020\277\021\022\027\n\022CSCDEFCloseRoomR"
    "sp\020\300\021\022\023\n\016CSCDEFReadyReq\020\301\021\022\031\n\024CSCDEFCanc"
    "elReadyReq\020\302\021\022\025\n\020CSCDEFKickoffReq\020\303\021\022\025\n\020"
    "CSCDEFKickoffRsp\020\304\021\022\023\n\016CSCDEFStartReq\020\305\021"
    "\022\035\n\030CSGetSpecActivityTimeReq\020\306\021\022\035\n\030CSGet"
    "SpecActivityTimeRsp\020\307\021\022\023\n\016CSCDEFStartRsp"
    "\020\310\021\022\021\n\014Announcement\020\311\021\022\036\n\031CSLoginAnnounc"
    "ementPreRsp\020\312\021\022\033\n\026CSLoginAnnouncementRsp"
    "\020\313\021\022\031\n\024CSAnnouncementPreRsp\020\314\021\022\026\n\021CSAnno"
    "uncementReq\020\315\021\022\026\n\021CSAnnouncementRsp\020\316\021\022\027"
    "\n\022CSMaAdvertisingRsp\020\317\021\022\014\n\007CSStyle\020\320\021\022\016\n"
    "\tCSMaStyle\020\321\021\022\035\n\030CSNotifyRewardToOtherRs"
    "p\020\322\021\022\017\n\nCSMailInfo\020\323\021\022\025\n\020CSGetMailListRe"
    "q\020\324\021\022\025\n\020CSGetMailListRsp\020\325\021\022\027\n\022CSSetMail"
    "StatusReq\020\326\021\022\027\n\022CSSetMailStatusRsp\020\327\021\022\032\n"
    "\025CSNotifyHasNewMailRsp\020\330\021\022\014\n\007CSPoint\020\240\037\022"
    "\024\n\017CSBattleMoveReq\020\241\037\022\024\n\017CSBattleMoveRsp"
    "\020\242\037\022\025\n\020MonsterMoveValue\020\243\037\022\025\n\020CSMonsterM"
    "oveRsp\020\244\037\022\026\n\021CSBattleCreateReq\020\245\037\022\026\n\021Mon"
    "sterBattleInfo\020\246\037\022\020\n\013MonsterInfo\020\247\037\022\026\n\021C"
    "SBattleCreateRsp\020\250\037\022\035\n\030CSBattleMonsterCr"
    "eateRsp\020\251\037\022\030\n\023CSBattleUserJoinRsp\020\252\037\022\031\n\024"
    "CSBattleUserLeaveRsp\020\253\037\022\034\n\027CSBattleLoadC"
    "ompleteReq\020\254\037\022\034\n\027CSBattleLoadCompleteRsp"
    "\020\255\037\022\025\n\020CSBattleLeaveReq\020\256\037\022\025\n\020CSBattleLe"
    "aveRsp\020\257\037\022\027\n\022CSBattleTimeoutRsp\020\260\037\022\031\n\024CS"
    "BattlePlayerDelRsp\020\261\037\022\035\n\030CSBattlePlayerR"
    "evivalReq\020\262\037\022\035\n\030CSBattlePlayerRevivalRsp"
    "\020\263\037\022\026\n\021AttackMonsterInfo\020\264\037\022\034\n\027CSAttackM"
    "onsterBackInfo\020\265\037\022\030\n\023CSMonsterAttackInfo"
    "\020\266\037\022\030\n\023CSMonsterEffectInfo\020\267\037\022\027\n\022CSMonst"
    "erAttackRsp\020\270\037\022\027\n\022CSMonsterEffectRsp\020\271\037\022"
    "\034\n\027CSMonsterBuffEffectInfo\020\272\037\022\024\n\017CSBuffE"
    "ffectRsp\020\273\037\022\024\n\017CSMonsterHitRsp\020\274\037\022\024\n\017CSS"
    "killBeginReq\020\275\037\022\024\n\017CSSkillBeginRsp\020\276\037\022\026\n"
    "\021CSPlayerAttackReq\020\277\037\022\026\n\021CSPlayerAttackR"
    "sp\020\300\037\022\025\n\020AttackPlayerInfo\020\301\037\022\031\n\024CSPlayer"
    "HitPlayerReq\020\302\037\022\031\n\024CSPlayerHitPlayerRsp\020"
    "\303\037\022\022\n\rCSPlayerHPRsp\020\304\037\022\022\n\rCSPlayerHPReq\020"
    "\305\037\022\026\n\021CSMonsterBloodRsp\020\306\037\022\024\n\017CSMonsterD"
    "ieReq\020\307\037\022\024\n\017CSMonsterDieRsp\020\310\037\022\027\n\022CSPlay"
    "erDieShowReq\020\311\037\022\027\n\022CSPlayerDieShowRsp\020\312\037"
    "\022\032\n\025CSPlayerMayImproveReq\020\313\037\022\032\n\025CSPlayer"
    "MayImproveRsp\020\314\037\022\025\n\020CSMonsterMoveReq\020\315\037\022"
    "\035\n\030CSBattleMonsterCreateReq\020\316\037\022\021\n\014CSCast"
    "leInfo\020\317\037\022\030\n\023CSBattleUserJoinReq\020\320\037\022\027\n\022C"
    "SMonsterCreateReq\020\321\037\022\027\n\022CSMonsterCreateR"
    "sp\020\322\037\022\020\n\013CSRangeInfo\020\360.\022\024\n\017CSMonsterInfo"
    "_t\020\361.\022\023\n\016CSMapMonster_t\020\362.\022\030\n\023CSMapMonst"
    "erGroup_t\020\363.\022\023\n\016CSMapContent_t\020\364.\022\027\n\022CSM"
    "apContentList_t\020\365.\022\025\n\020CSMonsterValue_t\020\366"
    ".\022\027\n\022CSBattlePrepareReq\020\367.\022\027\n\022CSBattlePr"
    "epareRsp\020\370.", 8091);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "head.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_head_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_head_2eproto {
  StaticDescriptorInitializer_head_2eproto() {
    protobuf_AddDesc_head_2eproto();
  }
} static_descriptor_initializer_head_2eproto_;

const ::google::protobuf::EnumDescriptor* CSMsgName_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgName_descriptor_;
}
bool CSMsgName_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 2000:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 2008:
    case 2009:
    case 2010:
    case 2011:
    case 2012:
    case 2013:
    case 2014:
    case 2015:
    case 2016:
    case 2017:
    case 2018:
    case 2019:
    case 2020:
    case 2021:
    case 2022:
    case 2023:
    case 2024:
    case 2025:
    case 2026:
    case 2027:
    case 2028:
    case 2029:
    case 2030:
    case 2031:
    case 2032:
    case 2033:
    case 2034:
    case 2035:
    case 2036:
    case 2037:
    case 2038:
    case 2039:
    case 2040:
    case 2041:
    case 2042:
    case 2043:
    case 2044:
    case 2045:
    case 2046:
    case 2047:
    case 2048:
    case 2049:
    case 2050:
    case 2051:
    case 2052:
    case 2053:
    case 2054:
    case 2055:
    case 2056:
    case 2057:
    case 2058:
    case 2059:
    case 2060:
    case 2061:
    case 2062:
    case 2063:
    case 2064:
    case 2065:
    case 2066:
    case 2067:
    case 2068:
    case 2069:
    case 2070:
    case 2071:
    case 2072:
    case 2073:
    case 2074:
    case 2075:
    case 2076:
    case 2077:
    case 2078:
    case 2079:
    case 2080:
    case 2081:
    case 2082:
    case 2083:
    case 2084:
    case 2085:
    case 2086:
    case 2087:
    case 2088:
    case 2089:
    case 2090:
    case 2091:
    case 2092:
    case 2093:
    case 2094:
    case 2095:
    case 2096:
    case 2097:
    case 2098:
    case 2099:
    case 2100:
    case 2101:
    case 2102:
    case 2103:
    case 2104:
    case 2105:
    case 2106:
    case 2107:
    case 2108:
    case 2109:
    case 2110:
    case 2111:
    case 2112:
    case 2113:
    case 2114:
    case 2115:
    case 2116:
    case 2117:
    case 2118:
    case 2119:
    case 2120:
    case 2121:
    case 2122:
    case 2123:
    case 2124:
    case 2125:
    case 2126:
    case 2127:
    case 2128:
    case 2129:
    case 2130:
    case 2131:
    case 2132:
    case 2133:
    case 2134:
    case 2135:
    case 2136:
    case 2137:
    case 2138:
    case 2139:
    case 2140:
    case 2141:
    case 2142:
    case 2143:
    case 2144:
    case 2145:
    case 2146:
    case 2147:
    case 2148:
    case 2149:
    case 2150:
    case 2151:
    case 2152:
    case 2153:
    case 2154:
    case 2155:
    case 2156:
    case 2157:
    case 2158:
    case 2159:
    case 2160:
    case 2161:
    case 2162:
    case 2163:
    case 2164:
    case 2165:
    case 2166:
    case 2167:
    case 2168:
    case 2169:
    case 2170:
    case 2171:
    case 2172:
    case 2173:
    case 2174:
    case 2175:
    case 2176:
    case 2177:
    case 2178:
    case 2179:
    case 2180:
    case 2181:
    case 2182:
    case 2183:
    case 2184:
    case 2185:
    case 2186:
    case 2187:
    case 2188:
    case 2189:
    case 2190:
    case 2191:
    case 2192:
    case 2193:
    case 2194:
    case 2195:
    case 2196:
    case 2197:
    case 2198:
    case 2199:
    case 2200:
    case 2201:
    case 2202:
    case 2203:
    case 2204:
    case 2205:
    case 2206:
    case 2207:
    case 2208:
    case 2209:
    case 2210:
    case 2211:
    case 2212:
    case 2213:
    case 2214:
    case 2215:
    case 2216:
    case 2217:
    case 2218:
    case 2219:
    case 2220:
    case 2221:
    case 2222:
    case 2223:
    case 2224:
    case 2225:
    case 2226:
    case 2227:
    case 2228:
    case 2229:
    case 2230:
    case 2231:
    case 2232:
    case 2233:
    case 2234:
    case 2235:
    case 2236:
    case 2237:
    case 2238:
    case 2239:
    case 2240:
    case 2241:
    case 2242:
    case 2243:
    case 2244:
    case 2245:
    case 2246:
    case 2247:
    case 2248:
    case 2249:
    case 2250:
    case 2251:
    case 2252:
    case 2253:
    case 2254:
    case 2255:
    case 2256:
    case 2257:
    case 2258:
    case 2259:
    case 2260:
    case 2261:
    case 2262:
    case 2263:
    case 2264:
    case 4000:
    case 4001:
    case 4002:
    case 4003:
    case 4004:
    case 4005:
    case 4006:
    case 4007:
    case 4008:
    case 4009:
    case 4010:
    case 4011:
    case 4012:
    case 4013:
    case 4014:
    case 4015:
    case 4016:
    case 4017:
    case 4018:
    case 4019:
    case 4020:
    case 4021:
    case 4022:
    case 4023:
    case 4024:
    case 4025:
    case 4026:
    case 4027:
    case 4028:
    case 4029:
    case 4030:
    case 4031:
    case 4032:
    case 4033:
    case 4034:
    case 4035:
    case 4036:
    case 4037:
    case 4038:
    case 4039:
    case 4040:
    case 4041:
    case 4042:
    case 4043:
    case 4044:
    case 4045:
    case 4046:
    case 4047:
    case 4048:
    case 4049:
    case 4050:
    case 6000:
    case 6001:
    case 6002:
    case 6003:
    case 6004:
    case 6005:
    case 6006:
    case 6007:
    case 6008:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace head_msg

// @@protoc_insertion_point(global_scope)
